#  ___ _            _ _    _ _    __
# / __(_)_ __  _ __| (_)__(_) |_ /_/
# \__ \ | '  \| '_ \ | / _| |  _/ -_)
# |___/_|_|_|_| .__/_|_\__|_|\__\___|
#             |_| Module: VelibDemo 4.0
paths:
  /login:
    get:
      summary: Login (obtain bearer token)
      security:
      - basicAuth: []
      produces:
      - text/plain
      - application/json
      operationId: login
      responses:
        '200':
          description: Successful login
        '401':
          schema:
            $ref: '#/definitions/Error401'
          description: Unauthorized
      parameters:
      - in: query
        name: _output
        description: Optional output format
        type: string
        required: false
        enum:
        - json
        - oauth2
        - token
      tags:
      - session
  /logout:
    get:
      summary: Logout (revoke bearer token)
      security:
      - bearerAuth: []
      produces:
      - application/json
      operationId: logout
      responses:
        '200':
          description: Successfull logout
        '401':
          schema:
            $ref: '#/definitions/Error401'
          description: Unauthorized
      tags:
      - session
  /rest/VelibComment:
    get:
      summary: Search VelibComment business object records or get contextualized metadata
      security:
      - bearerAuth: []
      produces:
      - application/json
      operationId: obj-velibcomment-search
      responses:
        '200':
          schema:
            $ref: '#/definitions/ArrayOfVelibComment'
          description: Success in searching business object records (or in getting
            contextualized business object metadata, documentation, ...)
        '401':
          schema:
            $ref: '#/definitions/Error401'
          description: Unauthorized
        '500':
          schema:
            $ref: '#/definitions/Error500'
          description: Internal server error
      parameters:
      - in: query
        name: _metadata
        description: Metadata?
        type: boolean
        required: false
      - in: query
        name: _count
        description: Count?
        type: boolean
        required: false
      - in: query
        name: _doc
        description: Documentation?
        type: boolean
        required: false
      - in: query
        name: velibCmtDateTime
        description: Search filter for Date/time
        type: string
        required: false
      - in: query
        name: velibCmtName
        description: Search filter for Name
        type: string
        required: false
      - in: query
        name: velibCmtStaId
        description: Search filter for Station
        type: string
        required: false
      - in: query
        name: velibCmtStaId__velibStaCode
        description: Search filter for Station code
        type: string
        required: false
      - in: query
        name: velibCmtStaId__velibStaName
        description: Search filter for Station name
        type: string
        required: false
      - in: query
        name: velibCmtEval
        description: Search filter for Evaluation
        type: integer
        required: false
      - in: query
        name: velibCmtComments
        description: Search filter for Comments
        type: string
        required: false
      - in: query
        name: velibCmtVisible
        description: Search filter for Visible?
        type: boolean
        required: false
      tags:
      - VelibComment
  /rest/VelibComment/{row_id}:
    post:
      summary: Create a new VelibCommentbusiness object record
      security:
      - bearerAuth: []
      produces:
      - application/json
      operationId: obj-velibcomment-create
      responses:
        '200':
          schema:
            $ref: '#/definitions/VelibComment'
          description: Success in creating a new business object record
        '400':
          schema:
            $ref: '#/definitions/Error400'
          description: Bad request
        '401':
          schema:
            $ref: '#/definitions/Error401'
          description: Unauthorized
        '500':
          schema:
            $ref: '#/definitions/Error500'
          description: Internal server error
      parameters:
      - in: path
        name: row_id
        description: Row ID (or empty or _ for all row IDs)
        type: string
        required: true
      - schema:
          $ref: '#/definitions/VelibComment'
        in: body
        name: body
      tags:
      - VelibComment
      consumes:
      - application/json
    get:
      summary: Get a VelibComment business object record
      security:
      - bearerAuth: []
      produces:
      - application/json
      operationId: obj-velibcomment-get
      responses:
        '200':
          schema:
            $ref: '#/definitions/VelibComment'
          description: Success in getting a single business object record
        '401':
          schema:
            $ref: '#/definitions/Error401'
          description: Unauthorized
        '500':
          schema:
            $ref: '#/definitions/Error500'
          description: Internal server error
        '404':
          schema:
            $ref: '#/definitions/Error404'
          description: Not found
      parameters:
      - in: path
        name: row_id
        description: Row ID (or empty or _ for all row IDs)
        type: string
        required: true
      - in: query
        name: _inline_documents
        description: Inline documents?
        type: boolean
        required: false
      - in: query
        name: _inline_thumbnails
        description: Inline documents' thumbnails?
        type: boolean
        required: false
      - in: query
        name: _inline_objects
        description: Inline objects?
        type: boolean
        required: false
      tags:
      - VelibComment
    delete:
      summary: Delete a VelibComment business object record
      security:
      - bearerAuth: []
      produces:
      - application/json
      operationId: obj-velibcomment-delete
      responses:
        '200':
          description: Success in deleting a business object record
        '400':
          schema:
            $ref: '#/definitions/Error400'
          description: Bad request
        '401':
          schema:
            $ref: '#/definitions/Error401'
          description: Unauthorized
        '500':
          schema:
            $ref: '#/definitions/Error500'
          description: Internal server error
        '404':
          schema:
            $ref: '#/definitions/Error404'
          description: Not found
      parameters:
      - in: path
        name: row_id
        description: Row ID (or empty or _ for all row IDs)
        type: string
        required: true
      tags:
      - VelibComment
    put:
      summary: Update a VelibCommentbusiness object record
      security:
      - bearerAuth: []
      produces:
      - application/json
      operationId: obj-velibcomment-update
      responses:
        '200':
          schema:
            $ref: '#/definitions/VelibComment'
          description: Success in updating a business object record
        '400':
          schema:
            $ref: '#/definitions/Error400'
          description: Bad request
        '401':
          schema:
            $ref: '#/definitions/Error401'
          description: Unauthorized
        '500':
          schema:
            $ref: '#/definitions/Error500'
          description: Internal server error
        '404':
          schema:
            $ref: '#/definitions/Error404'
          description: Not found
      parameters:
      - in: path
        name: row_id
        description: Row ID (or empty or _ for all row IDs)
        type: string
        required: true
      - schema:
          $ref: '#/definitions/VelibComment'
        in: body
        name: body
      tags:
      - VelibComment
      consumes:
      - application/json
  /rest/VelibStation/{row_id}:
    post:
      summary: Create a new VelibStationbusiness object record
      security:
      - bearerAuth: []
      produces:
      - application/json
      operationId: obj-velibstation-create
      responses:
        '200':
          schema:
            $ref: '#/definitions/VelibStation'
          description: Success in creating a new business object record
        '400':
          schema:
            $ref: '#/definitions/Error400'
          description: Bad request
        '401':
          schema:
            $ref: '#/definitions/Error401'
          description: Unauthorized
        '500':
          schema:
            $ref: '#/definitions/Error500'
          description: Internal server error
      parameters:
      - in: path
        name: row_id
        description: Row ID (or empty or _ for all row IDs)
        type: string
        required: true
      - schema:
          $ref: '#/definitions/VelibStation'
        in: body
        name: body
      tags:
      - VelibStation
      consumes:
      - application/json
    get:
      summary: Get a VelibStation business object record
      security:
      - bearerAuth: []
      produces:
      - application/json
      operationId: obj-velibstation-get
      responses:
        '200':
          schema:
            $ref: '#/definitions/VelibStation'
          description: Success in getting a single business object record
        '401':
          schema:
            $ref: '#/definitions/Error401'
          description: Unauthorized
        '500':
          schema:
            $ref: '#/definitions/Error500'
          description: Internal server error
        '404':
          schema:
            $ref: '#/definitions/Error404'
          description: Not found
      parameters:
      - in: path
        name: row_id
        description: Row ID (or empty or _ for all row IDs)
        type: string
        required: true
      - in: query
        name: _inline_documents
        description: Inline documents?
        type: boolean
        required: false
      - in: query
        name: _inline_thumbnails
        description: Inline documents' thumbnails?
        type: boolean
        required: false
      - in: query
        name: _inline_objects
        description: Inline objects?
        type: boolean
        required: false
      tags:
      - VelibStation
    delete:
      summary: Delete a VelibStation business object record
      security:
      - bearerAuth: []
      produces:
      - application/json
      operationId: obj-velibstation-delete
      responses:
        '200':
          description: Success in deleting a business object record
        '400':
          schema:
            $ref: '#/definitions/Error400'
          description: Bad request
        '401':
          schema:
            $ref: '#/definitions/Error401'
          description: Unauthorized
        '500':
          schema:
            $ref: '#/definitions/Error500'
          description: Internal server error
        '404':
          schema:
            $ref: '#/definitions/Error404'
          description: Not found
      parameters:
      - in: path
        name: row_id
        description: Row ID (or empty or _ for all row IDs)
        type: string
        required: true
      tags:
      - VelibStation
    put:
      summary: Update a VelibStationbusiness object record
      security:
      - bearerAuth: []
      produces:
      - application/json
      operationId: obj-velibstation-update
      responses:
        '200':
          schema:
            $ref: '#/definitions/VelibStation'
          description: Success in updating a business object record
        '400':
          schema:
            $ref: '#/definitions/Error400'
          description: Bad request
        '401':
          schema:
            $ref: '#/definitions/Error401'
          description: Unauthorized
        '500':
          schema:
            $ref: '#/definitions/Error500'
          description: Internal server error
        '404':
          schema:
            $ref: '#/definitions/Error404'
          description: Not found
      parameters:
      - in: path
        name: row_id
        description: Row ID (or empty or _ for all row IDs)
        type: string
        required: true
      - schema:
          $ref: '#/definitions/VelibStation'
        in: body
        name: body
      tags:
      - VelibStation
      consumes:
      - application/json
  /:
    get:
      summary: Get user session information
      security:
      - bearerAuth: []
      produces:
      - application/json
      operationId: info
      responses:
        '200':
          description: Success in getting user session information
        '401':
          schema:
            $ref: '#/definitions/Error401'
          description: Unauthorized
      parameters:
      - in: query
        name: texts
        description: Texts?
        type: boolean
        required: false
      tags:
      - session
  /rest/VelibStation:
    get:
      summary: Search VelibStation business object records or get contextualized metadata
      security:
      - bearerAuth: []
      produces:
      - application/json
      operationId: obj-velibstation-search
      responses:
        '200':
          schema:
            $ref: '#/definitions/ArrayOfVelibStation'
          description: Success in searching business object records (or in getting
            contextualized business object metadata, documentation, ...)
        '401':
          schema:
            $ref: '#/definitions/Error401'
          description: Unauthorized
        '500':
          schema:
            $ref: '#/definitions/Error500'
          description: Internal server error
      parameters:
      - in: query
        name: _metadata
        description: Metadata?
        type: boolean
        required: false
      - in: query
        name: _count
        description: Count?
        type: boolean
        required: false
      - in: query
        name: _doc
        description: Documentation?
        type: boolean
        required: false
      - in: query
        name: _indexsearch
        description: Index search query
        type: string
        required: false
      - in: query
        name: _crosstab
        description: Apply pivot table
        type: string
        required: false
        enum:
        - VelibStation
      - in: query
        name: _crosstabcubes
        description: Pivot table data as cubes?
        type: boolean
        required: false
      - in: query
        name: velibStaCode
        description: Search filter for Station code
        type: string
        required: false
      - in: query
        name: velibStaName
        description: Search filter for Station name
        type: string
        required: false
      - in: query
        name: velibStaCoordinates
        description: Search filter for Station coordinates
        type: string
        required: false
      - in: query
        name: velibStaStatus
        description: Search filter for Station status
        type: string
        required: false
        enum:
        - OPERATIVE
        - WORKINPROGRESS
        - CLOSE
      - in: query
        name: velibStaBikes
        description: Search filter for Number of available bikes
        type: integer
        required: false
      - in: query
        name: velibStaFreeDocks
        description: Search filter for Number of free docks
        type: integer
        required: false
      - in: query
        name: velibStaMonitoring
        description: Search filter for Monitoring?
        type: boolean
        required: false
      - in: query
        name: velibStaRating
        description: Search filter for Rating
        type: integer
        required: false
      - in: query
        name: velibStaComments
        description: Search filter for Comments
        type: string
        required: false
      tags:
      - VelibStation
securityDefinitions:
  basicAuth:
    type: basic
  bearerAuth:
    in: header
    name: Authorization
    type: apiKey
definitions:
  Error404:
    type: object
    properties:
      error:
        description: Error message
        type: string
      status:
        description: Error status
        type: integer
        enum:
        - 404
  VelibStation:
    type: object
    properties:
      velibStaComments:
        description: Comments
        type: string
      velibStaName:
        description: Station name
        type: string
      velibStaCoordinates:
        description: Station coordinates
        type: string
      velibStaMonitoring:
        description: Monitoring?
        type: boolean
      row_id:
        description: Unique technical row ID
        type: string
      velibStaCode:
        description: Station code
        type: string
      velibStaStatus:
        description: Station status
        type: string
        enum:
        - OPERATIVE
        - WORKINPROGRESS
        - CLOSE
      velibStaBikes:
        description: Number of available bikes
        type: integer
      velibStaFreeDocks:
        description: Number of free docks
        type: integer
      velibStaRating:
        description: Rating
        type: integer
  ActionResult:
    type: object
    properties:
      result:
        description: Action result
        type: string
  ArrayOfVelibStation:
    type: array
    items:
      $ref: '#/definitions/VelibStation'
  TreeviewData:
    type: object
    properties:
      item:
        description: Object item with lists of linked objects' items
        type: object
  PublicationResult:
    type: object
    properties:
      mime:
        description: MIME type
        type: string
      content:
        description: Content (plain text or base64 encoded)
        type: string
  Error400:
    type: object
    properties:
      error:
        description: Error message
        type: string
      status:
        description: Error status
        type: integer
        enum:
        - 400
  ArrayOfVelibComment:
    type: array
    items:
      $ref: '#/definitions/VelibComment'
  Error401:
    type: object
    properties:
      error:
        description: Error message
        type: string
      status:
        description: Error status
        type: integer
        enum:
        - 401
  Error500:
    type: object
    properties:
      error:
        description: Error message
        type: string
      status:
        description: Error status
        type: integer
        enum:
        - 500
  VelibComment:
    type: object
    properties:
      velibCmtEval:
        description: Evaluation
        type: integer
      velibCmtStaId__velibStaCode:
        description: Station code
        type: string
      velibCmtName:
        description: Name
        type: string
      velibCmtComments:
        description: Comments
        type: string
      velibCmtDateTime:
        description: Date/time
        type: string
      row_id:
        description: Unique technical row ID
        type: string
      velibCmtVisible:
        description: Visible?
        type: boolean
      velibCmtStaId__velibStaName:
        description: Station name
        type: string
      velibCmtStaId:
        description: Station
        type: string
  Error403:
    type: object
    properties:
      error:
        description: Error message
        type: string
      status:
        description: Error status
        type: integer
        enum:
        - 403
swagger: '2.0'
info:
  license:
    name: Simplicite license
    url: http://www.simplicitesoftware.com
  contact:
    name: Simplicite Software
    url: http://www.simplicitesoftware.com
    email: contact@simplicitesoftware.com
  description: API for module VelibDemo
  title: VelibDemo
  version: '4.0'
tags:
- name: VelibComment
  description: User comment
- name: VelibStation
  description: Station
